### ISSUE TITLE
chromedriver unexpectedly exited. Status code was: 1

### ISSUE THREAD

**Issue by faizananwerali** [brutalsavage/facebook-post-scraper#19]
Any idea what is wrong? 
My Command:

    python scraper.py -p "https://www.facebook.com/icc/" -l 10

Error:

    Traceback (most recent call last):
      File "scraper.py", line 322, in <module>
        postBigDict = extract(page=args.page, numOfPost=args.len, infinite_scroll=infinite,     scrape_comment=scrape_comment)
      File "scraper.py", line 256, in extract
        browser = webdriver.Chrome(executable_path="./chromedriver", options=option)
      File "/home/visionph/virtualenv/py.sayfcodes.com/3.7/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
        self.service.start()
      File "/home/visionph/virtualenv/py.sayfcodes.com/3.7/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 98, in start
        self.assert_process_still_running()
      File "/home/visionph/virtualenv/py.sayfcodes.com/3.7/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
        % (self.path, return_code)
    selenium.common.exceptions.WebDriverException: Message: Service ./chromedriver unexpectedly exited. Status code was: 1

**Comment by AS7RIDENIED** [comment]
Are you fix it? I have some problem on vds server

**Comment by AS7RIDENIED** [comment]
> Are you fix it? I have some problem on vds server

I fixed it. In the settings of my bot, the webdriver logs should have gone to drive D, but I only had one - C. After changing the drive letter, the problem was solved
